apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: px-eksctl
  region: ap-northeast-1
  version: "1.20"
managedNodeGroups:
  - name: storage-nodes
    instanceType: m5.xlarge
    minSize: 3
    maxSize: 3
    volumeSize: 20
    #ami: auto
    amiFamily: AmazonLinux2
    labels: {role: worker, "portworx.io/node-type": "storage"}
    tags:
      nodegroup-role: worker
    ssh:  
      allow: true
      publicKeyPath: ~/.ssh/aws-vm.pub
      publicKeyName: pxhandson
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::011023878950:policy/portworx_for_EKS #Portworx用に作成したIAM PolicyのARN Name
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true
vpc:
  id: "vpc-063d8891587669e75"
  subnets:
    public:
      ap-northeast-1c:
        id: "subnet-00cdc9a7d53cb4936"
      ap-northeast-1a:
        id: "subnet-01a50944999181547"
      ap-northeast-1d:
        id: "subnet-0211883aec409d0e1"
